# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: 
date_format: "ordinal"
title: YUNCHOW在扯淡
subtitle: "初心不负，终将不凡"
description: "YUNCHOW在扯淡"
keywords: zhouyun, yunchow, zhy, yunchow.zy
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 1

# ---------------- #
#      Author      #
# ---------------- #
author: YUNCHOW
organization: yunchow.com
organization_url: http://www.yunchow.com
github_username: YUNCHOW
location: 中国・杭州
email: yunchow.zy@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /open-source/
    label: 开源

  -
   href: /about/
   label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 18
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
#    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: yunchow/yunchow.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, livere

# https://livere.com/introduce
comments_provider: livere
livere:
    user_token: MTAyMC8zMTA3Mi83NjIw
# https://disqus.com
disqus:
    username: yunchow
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: YUNCHOW
    repo: blog-comments
    oauth:
        client_id: b9b3321130883bd874ae
        client_secret: b6625ead5f7e1e38e0fe34e609130a934b955462
# 在使用其它评论组件时可点击显示 Disqus
# lazy_load_disqus : true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-106899440-1
baidu:
    analytics_id: 4ef0c059eb528a0911c561c042f19ae7

